---

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    lbserver:
      hosts:
        172.17.0.2:
    dbserver:
      hosts:
        172.17.0.3:
    webserver:
      hosts:
        172.17.0.4:
        172.17.0.5:

...
