---
collections:
# With just the collection name
- projet6.my_collection

# With the collection name, version, and source options
- name: pp.my_other_collection
  version: 'version range identifiers (default: ``*``)'
  source: 'The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)'

  ...
