---
- name: "[php8_fpm] - reload php8.0-fpm"
  service:
    name: php8.0-fpm
    state: restarted

- name: "[WORDPRESS] - check if wordpress exist"
  stat:
    path: "/var/www/html/wordpress"
  register: check_wordpress

- name: "[WORDPRESS] - download wordpress"
  unarchive:
    src: "{{ wordpress_source }}"
    dest: /var/www/html
    remote_src: yes
  when: check_wordpress.stat.exists == False
  run_once: yes

- name: "[WORDPRESS] - index.html"
  file:
    path: "/var/www/html/index.html"
    state: absent

- name: "[WORDPRESS] - wp-config-sample.php existe"
  stat:
    path: "/var/www/html/wordpress/wp-config-sample.php"
  register: check_sample

- name: "[WORDPRESS] - renomme wp-config-sample.php"
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  when: check_sample.stat.exists == True

- name: "[WORDPRESS] - config  wp-config.php"
  lineinfile:
    dest: "/var/www/html/wordpress/wp-config.php"
    regexp: "{{ item.search }}"
    line: "{{ item.new }}"
    backrefs: yes
  with_items:
    - {'search': '^(.)database_name_here(.*)$', 'new': '\1{{ mysql_db }}\2'}
    - {'search': '^(.)username_here(.*)$', 'new': '\1{{ mysql_user }}\2'}
    - {'search': '^(.)password_here(.*)$', 'new': '\1{{ mysql_password }}\2'}
    - {'search': '^(.)localhost(.*)$', 'new': '\1{{ mysql_host }}\2'}



...
