---

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart webserver
  service:
    name: "{{ apache2_http_name }}"
    state: restarted

- name: reload webserver
  service:
    name: "{{ apache2_http_name }}"
    state: reloaded

# handlers file for wordpress

...
